### ISSUE TITLE
minor bug fixes

### ISSUE THREAD

**Issue by DXsyntax** [cchousesc/virtual_SAC#8]
follow these appropriately,  FOLLOW UP UPDATE ON - 19th july, pls indicate which is done and not done by adding a DONE next to the task. e.g 
first task **DONE**
second task **IN PROG**

go to the code tab ->
click on code -> 
download as zip 

this is to prepare you to learn how to clone repo from your terminal 

_pls ask me questions on anything you find you don't understand in this code tab, including when you click code to download the files_

when working on your laptop, **please change systems display resolution to 100%** to avoid conflict of screen sizes
**in browser** please make sure resolution is **adjusted to 100%** also

1. fix homepage footer to fit 100% resolution

2. fix navbar across website to spread tabs out evenly

3. fix picture alignments to center in EVENTS section. including the last 4 pictures in grid format. pls center it

4. pls comment out sc logo and the word "test" from footer

5. please choose appropriate font for artpicks section, if you feel its not required and its good as it is just highlight it when you are done.

6. pls choose appropriate font for ENRICHMENT section too. 

7. pls choose appropriate font for workshops section too.

**Comment by pika-ranger** [comment]
first task **IN PROG**
second task **DONE**
third task **IN PROG**
fourth task **DONE**
fifth task **DONE**
sixth task **DONE**
seventh task **DONE**
